# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: NBS monthly report - 2024 March
author: MET Norway - NBS team
#logo: logo.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  stderr_output: remove-warn

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: month.tex
  latex_elements:
    maketitle: |
      \begin{titlepage}
      \centering
      \vspace*{2cm}
      {\Huge \textbf{\thetitle}\par}
      \vspace{1.5cm}
      {\Large \textbf{\theauthor}\par}
      \vfill
      % Omit the date here
      \end{titlepage}

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
 # - cryoS.bib

# Format the citation style
sphinx:
  config:
    bibtex_reference_style: author_year
    html_show_copyright: false


# Information about where the book exists on the web
repository:
  url: https://github.com/NasjonaltBakkeSegment/NBS_monthly_reports # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true
  extra_footer: |
    <p>
    This Report is part of the NBS project.
    <br>
    The Norwegian Space Agency is not responsible in any way for the content of this document.
    </p>
